### ISSUE TITLE
Query by identifier

### ISSUE THREAD

**Issue by nichtich** [rero/rero-mef#30]
There should be a documented method to query a record by its identifier, e.g. http://catalogue.bnf.fr/ark:/12148/cb100492988

**Comment by nichtich** [comment]
Thanks for the detailed instruction to get to the URI from a search. I was looking for the opposite direction: if I only have the BNF URI, how can I get to the MEF record?

**Comment by iGormilhit** [comment]
I've just tried this: https://mef.test.rero.ch/api/mef/?q="http://catalogue.bnf.fr/ark:/12148/cb100492988"&prettyprint=1 

If you want to query with the ID itself, it's a bit complicated, because from `cb100492988` you'll need to extract the ID, which seems to be `10049298`: https://mef.test.rero.ch/api/mef/?q=bnf.bnf_pid:10049298&prettyprint=1

But you're right, nothing is really documented yet... :slightly_smiling_face:
